### ISSUE TITLE
Custom domains should only route access to the owner's page and posts

### ISSUE THREAD

**Issue by sclevine** [standardnotes/listed#1]
Follow up from this Slack thread:
https://standardnotes.slack.com/archives/C9W5BNKC0/p1551407188003700

I haven't had a chance to setup a local server with test data to try this out yet, but here's a suggestion for a fix. Let me know if this seems reasonable.

First, wrap these lines in a new `constraints` block that matches the opposite of `CustomDomainConstraint`:
https://github.com/standardnotes/listed/blob/3c3d77b94819dd950edee2976c4e26c6b24342b6/config/routes.rb#L49-L69

Next, check that the post's author's custom domain matches the request's domain in `posts#show`, and 404 if not:
https://github.com/standardnotes/listed/blob/3c3d77b94819dd950edee2976c4e26c6b24342b6/app/controllers/posts_controller.rb#L28-L50

I don't work with rails very often. There are probably better idioms for this type of behavior that I'm not aware of. 😅

**Comment by atmoio** [comment]
Hmm yeah, something like this could work. I'd have to take a deeper look once I'm back in this codebase. Can't make any promises as to when, but I agree this would be very good to have.
