### ISSUE TITLE
Page scroll position is maintained when navigating to some Listed blogs from main page

### ISSUE THREAD

**Issue by xeluna** [standardnotes/listed#100]
**Describe the bug**

I don't know exactly when this started, but recently I've noticed it when navigating to various Listed blogs from the front page that my scroll position is maintained, so I end up somewhere in the middle of the page instead of the top of the page. I've tried this in private browsing/incognito windows too.

If you turn off JavaScript, then this problem goes away, so there must be something that is remembering the scroll position, but applying it wrongly to the page. There is also no problem if you open the blog in a new tab or window. 

I'm unfortunately unable to tell you what causes the problem or what the blogs that exhibit this behavior have in common; only which blogs I've noticed currently on the front page have this problem.

**To Reproduce**

1. Visit [the Listed homepage](https://listed.to/) 
2. Scroll down to the Recent Authors section and click to view a blog that has this issue (pick any of the blogs listed below that are said to have the issue, **do not** open in a new tab, do not open the links directly from below).

Blogs that have this issue (not an exhaustive list):

1. [Scott McClung](https://listed.to/@scottmcclung)
2. [All Is Well in the Great Mess](https://listed.to/@alliswellinthegreatmess)
3. [@branches](https://listed.to/@branches)
4. [Wada](https://listed.to/@wada)
5. [100 Suns](https://listed.to/@100suns)

Blogs that **don't** have this issue (not an exhaustive list):

1. [Asphalt](https://changelog.asphaltbot.com/)
2. [Darryl Mitchell](https://listed.to/@darrmit)
3. [Teo Oliver](https://listed.to/@teooliver)
4. [來來](https://listed.to/@lailai)

**Expected behavior**

1. Scroll position should be at the top of the page (not my scroll position on the Listed homepage).

**Desktop**
OS: MacOS
Browser: Tested and reproduced with Firefox, Chrome, and Safari

**Comment by JaspalSuri** [comment]
Hi @xeluna,

Thank you for reporting this issue and for all of those details! I was able to reproduce this issue and I've created a ticket for the dev team to review.
