### ISSUE TITLE
Order of authors in recent authors section can be manipulated for potential benefit

### ISSUE THREAD

**Issue by balance-wtf** [standardnotes/listed#103]
The `recent authors` section on [listed.to](https://listed.to) is not really "recent", since anyone can put a date well into the future. Kind of unfair to the people posting honest work every day. Currently the section is bloated by blogs who have put in dates like "December 31st, 9999", or "December 1st, 2030". Think the mechanism behind this needs to be re-worked so that it counts the date a post gets pushed to the site, or the `created_at` value, but only when it is in the past.

**Comment by JaspalSuri** [comment]
Hi @aaantoszek,

I've responded to the thread on Slack and have created a report for this issue, but am leaving a comment here for anyone else who comes across this thread.

Thanks for opening an issue on GitHub. 🙂

**Comment by atmoio** [comment]
Ha, didn't realize that's what they were doing. We'll get a fix in for this, but its requires some new DB fields, so it won't be right away.

**Comment by atmoio** [comment]
Went with a simpler solution :)

**Comment by balance-wtf** [comment]
Thanks so much for the quick fix @mobitar @karolsojko 🙌
