### ISSUE TITLE
Verify Subsrcription

### ISSUE THREAD

**Issue by cr7yash** [standardnotes/listed#118]
![Screenshot from 2021-02-18 13-30-03](https://user-images.githubusercontent.com/15312466/108324091-7770c880-71ed-11eb-941e-0815d11db07e.png)

I am trying to subscribe to my blog but when I am trying to complete the captcha verification step, it doesn't lead to successful completion but refreshes to generate a new captcha. Tried it 5-6 times to no avail.

**Comment by JaspalSuri** [comment]
Hi @cr7yash,

I'm sorry to hear that. I'm afraid I was unable to reproduce the issue as I was able to subscribe to your blog. What browser are you using and what extensions are installed on it? Does it allow you to subscribe again at the moment? Can you try subscribing with a different email address?

Edit: according to another thread, you're using the Brave Browser. What operating system is it running on?

**Comment by cr7yash** [comment]
I am using brave browser with Ubuntu. Yes, some people were able to subscribe but I received no email of the subscription plus I am not able to manage my subscribers. I confirmed my subscription with other accounts, still didn't receive mail about subscription.

**Comment by JaspalSuri** [comment]
If I'm not mistaken, the subscribers list is currently not available to authors to help preserve the subscribers' privacy. If they'd like to reach out to you, they can sign your Guestbook. 🙂

**Comment by cr7yash** [comment]
Oh yes, I understand now. Privacy is central to the product. Got it Jaspal!
