### ISSUE TITLE
Option to set description meta tag in post metadata

### ISSUE THREAD

**Issue by crabmusket** [standardnotes/listed#119]
**Proposal:**

Read a `description` property from post metadata, e.g.:

```
---
description: A post on my blog!
---

post content
```

This should render a `meta` tag in the post:

```html
<meta content="A post on my blog!" name="description"/>
```

**Motivation:**

When sharing posts on social media, it's nice to be able to provide a summary tailored for that use-case.

Other options to control metadata of posts are available ([see docs](https://docs.standardnotes.org/listed/options/)).

**Alternatives:**

Currently, the description meta tag is created automatically from the post content. See [here](https://github.com/standardnotes/listed/blob/a2fc7ca975e6d7ada54e177867083b228a6ca77c/app/views/layouts/application.html.erb#L8) and [here](https://github.com/standardnotes/listed/blob/a2fc7ca975e6d7ada54e177867083b228a6ca77c/app/views/layouts/application.html.erb#L18).

```ruby
@desc = strip_tags(@post.rendered_text).slice(0, 200) + "..."
```

This is a sensible default. However, per the **motivation** above, the beginning of an article isn't necessarily a good summary, and is not tailored for the purpose of sharing.

---

I'm happy to contribute the code for this feature if you guys want it. It seems I can copy most of the code used to implement the `canonical` meta property. I would also move the code to calculate the description (e.g. either the `description` meta property, or the first 200 chars of the content) into the Post model class.

As per the longevity statement, I'm not sure how to evaluate the impact this would have. It'd be more code and more database columns, but I do feel like sharing blog posts is an important and attractive use-case.

**Comment by atmoio** [comment]
I like this idea 👍

**Comment by t-var-s** [comment]
I would like to +1 this, specially if within the same logic we can generate all the usual meta tags like:

```html
<meta name="title" content="A title for my blog">
<meta name="description" content="A post on my blog!">
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://standardnotes.org">
<meta property="twitter:title" content="A title for my blog">
<meta property="twitter:description" content="A post on my blog!">
<meta property="twitter:image" content="https://standardnotes.org/assets/icon.png">
<meta property="og:type" content="website">
<meta property="og:url" content="https://standardnotes.org">
<meta property="og:title" content="A title for my blog">
<meta property="og:description" content="A post on my blog!">
<meta property="og:image" content="https://standardnotes.org/assets/icon.png">

```

**Comment by crabmusket** [comment]
I agree that more meta tags would be good, but does that mean a new database column for each of them? :sweat_smile:

**Comment by t-var-s** [comment]
> I agree that more meta tags would be good, but does that mean a new database column for each of them? 

Maybe just the description and an URL for the image? Personally, I don't see much of an issue with og:image being the same as twitter:image.

**Comment by atmoio** [comment]
Meta description tag is now available via `desc` property: https://standardnotes.com/help/67/how-do-i-specify-a-custom-date-for-a-post-or-set-the-canonical-url
