### ISSUE TITLE
HOST environment variable not used in .jsx files

### ISSUE THREAD

**Issue by jelkose** [standardnotes/listed#121]
Hey,
I'm working with standardnotes for years now, it's awesome!
My notes are currently lying on my own server, and I'm using some additional external editors with my extended subscription.
Now I'd like to share my notes with other people by running the listed extension locally.

I just got it running in a subdirectory of my server. I've added the full address to the "HOST" variable in the .env-file, but some template files do not seem to include this environment-variable to their XHR-request-paths. 
The problem occurs first if I try to click the "Start writing" button: It seems like the path in line 17 in file [StartWriting.jsx](https://github.com/standardnotes/listed/blob/develop/client/app/components/shared/StartWriting.jsx) is defined the root of the website without using the HOST variable:
` ... .post("/authors", null, { ...`
After doing quick search in the repository there seem to be some more files including this thing.

I think changing this might help other people trying to self-host the listed-extension in a subdirectory.

Cheers,
Jelko

**Comment by jelkose** [comment]
For anyone who might be interested in a "quick-and-dirty" solution:
I've just added the line 
```
axios.defaults.baseURL = "YOUR URL";
```
right after the imports to any file using the axios module, which seems to use the website root as default for it's ```baseURL```.

I couldn't get the more general solution by using
```
axios.defaults.baseURL = process.env.REACT_APP_HOST;
```
instead of the above line to work. This would enable users to set the BaseURL by adding the corresponding value to REACT_APP_HOST in the .env file. But it seems like the dotenv-plugin would be needed therefor.

I think it should not be a problem for You to implement this to solution, if You'd like to expand the use cases of listed. If not just feel free to close this issue.

**Comment by antsgar** [comment]
Hi @jelkose! How are you doing? 🙂

First of all, so sorry for the delay addressing this. I noticed there's an open PR to fix this, but wanted to check with you first, when you click on the "Start writing" button on your self-hosted Listed website, what's the complete path the request is made to? Since the request path is root-relative, I think the complete path should start with your own website's root URL, but I might be missing something. Please let me know!

**Comment by jelkose** [comment]
Hey @antsgar! I'm fine, hope You're too!
No worries, if I've had more time, I'd sooner have investigated in this by myself.

There is a POST-Request resulting in a 404 going to ```https://MY.DOMAIN/authors```, but as I've set the HOST environment-variable to ```https://MY.DOMAIN/sn_listed``` it should be made to ```https://MY.DOMAIN/sn_listed/authors```.

I think this is caused by axios using the root URL instead of what I've set as HOST.

The pull request resolves another issue with the same symptom: After fixing the above, a call to ```https://MY.DOMAIN/new_author``` is made, wheter it should go to ```https://MY.DOMAIN/sn_listed/new_author```. I think here someone just missed adding ```#{ENV['HOST']}``` to the ```redirect_to``` variable in ```app/controllers/authors_controller.rb```, as this is prepended to the URL in any other ruby file.

**Comment by antsgar** [comment]
Thanks for your reply @jelkose! I understand now, makes sense. I think you might run into the same problem with this line here https://github.com/standardnotes/listed/blob/fb4d692b90fe0c9fafe071517f9d354a72a86753/app/controllers/application_controller.rb#L47 Feel free to update your PR changing that line too, if you think it'd be useful 🙂

I'll also be taking a look at your proposed solution for fixing this for Axios requests, I think it could work but might be worth testing it out a bit just in case. Thank you so much for your feedback and input!

**Comment by jelkose** [comment]
Well, I did not so far. But maybe that's only a question of time 😄 
I'll update my PR with the according lines.

You're welcome, thank You for Your help!

**Comment by antsgar** [comment]
@jelkose you're welcome! The PR is already merged 😄 please don't hesitate to reach out if you run into any more issues!
