### ISSUE TITLE
Hard-coded colors and miss-match between SCSS and CSS variables make custom themes hard to implement

### ISSUE THREAD

**Issue by lissy93** [standardnotes/listed#151]
Loving you're new Listed design! I just tried to theme my blog, and hit an issue with the color variables-  the page has CSS variables, which is awesome- but they're not being properly used. There are instances of hard-coded color values, as well as pre-compiled variables. 

This makes the blog much harder to customize for end users, (especially compared the the previous version of Listed). After setting all the values outlined in the [docs](https://standardnotes.org/help/66/how-do-i-change-the-colors-fonts-and-general-layout-of-my-listed-blog), a large proportion of the blog page remains in the original colors (which breaks things if you're making a dark theme). 

There's a mismatch between SCSS and CSS variables. In the interest of extensibility, only CSS variables should be used, since SASS is compiled at build time, it means that users using the hosted instance of Listed cannot easily override colors to theme their page (without targeting individual components by their selectors). It looks like a solution for this started to be implemented in [`vars.scss`](https://github.com/standardnotes/listed/blob/develop/client/app/assets/styles/vars.scss#L82), but most colors do not use these variables. There are 300+ instances of this.

There are also instances which are not using variables, and just have hard-coded hex values. E.g.
- `.author-post` has `background-color: #F8F9FC` in [`carded-blog.scss`](https://github.com/standardnotes/listed/blob/develop/app/assets/stylesheets/carded-blog.scss#L14)
- `.post-body p code` has `background-color: #f7f7f9;` and `border: 1px solid #e1e1e8;` in [`Post.scss`](https://github.com/standardnotes/listed/blob/develop/client/app/components/posts/Post.scss#L56)

**Comment by JaspalSuri** [comment]
Hi @Lissy93! Thanks for taking the time to report this. I'll forward this to one of our devs who is currently working on Listed. 🙂

**Comment by lissy93** [comment]
Thank you :)
I'd be happy to help out with a PR if you'd like

**Comment by daianaszwimer** [comment]
Hi @Lissy93 ! How are you?

[I just created a PR](https://github.com/standardnotes/listed/pull/152) so you don't have to worry about that 😄
Thank you for reporting this!

Have a nice day 😌

**Comment by lissy93** [comment]
That was quick- thank you very much 😄 
It might be good in the future to have all components using CSS variables, so that users can easily theme their blogs?

**Comment by daianaszwimer** [comment]
Hi @Lissy93 !

From what I can see, almost every component that has color uses CSS variables (I think there are only two places that use hardcoded colors, I will change that ASAP).

You can theme your blog with custom CSS **and** you can change the blog layout on Settings -> Appearance 😎

Let me know if there's anything else I can help you with! 😃

**Comment by lissy93** [comment]
> From what I can see, almost every component that has color uses CSS variables (I think there are only two places that use hardcoded colors, I will change that ASAP).

Hi @daianaszwimer  thanks for you're reply 😃  I might be missing something, sorry if I'm just being dumb here, but when making a theme for my blog, a lot of the colors have to be overridden by selector (rather than variable). For example:
- `#author-profile` background in [`Show.scss`](https://github.com/standardnotes/listed/blob/develop/client/app/components/authors/Show.scss#L3)
- `.footer--blog-page` background in [`Footer.scss`](https://github.com/standardnotes/listed/blob/develop/client/app/components/shared/Footer.scss#L26)
- `.page-header__container--post` background in [`HeaderContainer.scss`](https://github.com/standardnotes/listed/blob/develop/client/app/components/authors/HeaderContainer.scss#L29)
- `#single-post-footer` background in [`Show.scss`](https://github.com/standardnotes/listed/blob/develop/client/app/components/posts/Show.scss#L40)
- `.callout` background in [`application.scss`](https://github.com/standardnotes/listed/blob/develop/client/app/assets/styles/application.scss#L287)
- `.scroll-to-top__container` and `.button.scroll-to-top__button` background in [`ScrollToTopButton.scss`](https://github.com/standardnotes/listed/blob/develop/client/app/components/shared/ScrollToTopButton.scss#L15)

This is because, in these instances the app is using SASS/ SCSS variables (`$color`) for colors (as opposed to CSS `var(--color)`), and SCSS is compiled at build time, which means the variables cannot be modified by the user in the production application.  e.g. take a look at the gradient background for `.button--primary` in [`application.scss`](https://github.com/standardnotes/listed/blob/develop/client/app/assets/styles/application.scss#L202) - it has two colors: the second is a CSS variable (and it is easily modifiable by the user), but the first value is a SASS variable (so appears as a hex code in the built app)

So for the user to apply custom colors, they must target elements individually by their selectors, and override the existing styles. Not the end of the world at all, but it makes things a little harder for the user, and may mean that any changes in the markup or class names could break the users theme.

**Comment by daianaszwimer** [comment]
Hi @Lissy93 !

Ohhh yes! You're right, I searched for `#` in the code and forgot about the places that use `$`, thank you for the heads up! I'll fix that ASAP 😄  🤩

**Comment by daianaszwimer** [comment]
Hi @Lissy93 !

Here's the PR with almost all of the missing variables. It will soon be deployed to production! 😄 
https://github.com/standardnotes/listed/pull/164

Thank you!

**Comment by lissy93** [comment]
Awesome, thanks very much for doing that :)
