### ISSUE TITLE
Numbers cut off on new website

### ISSUE THREAD

**Issue by OddHouseGames** [standardnotes/listed#156]
Not sure if this is just on my end, but on desktop and mobile the numbers on the updated version of the website are cut off.![image](https://user-images.githubusercontent.com/62911518/114159739-1b284c00-98f4-11eb-8ad3-32f8368a9a21.jpeg)

**Comment by JaspalSuri** [comment]
Hi @OddHouseGames, this is an intentional part of the redesign. 🙂 Thanks for asking about this; I'll pin this thread temporarily.

**Comment by OddHouseGames** [comment]
Hi Jaspal, thanks for letting me know. I had considered that as a possibility, but it was the '2' that threw me off, it may look better adjusted vertically just slightly.

Either way, I really like the new Listed look and kudos to the team!

**Comment by JaspalSuri** [comment]
On behalf of the dev team, thanks for the kinds words!
