### ISSUE TITLE
Repetition on listed.io

### ISSUE THREAD

**Issue by OddHouseGames** [standardnotes/listed#158]
It may be beneficial to consider reducing written repetition on the listed.io blog as it shows the title and logo many times.

Or see if it is possible to just hide the page title and L image to avoid the duplication.

![image](https://user-images.githubusercontent.com/62911518/114160922-7149bf00-98f5-11eb-9f81-fadd93ab3cbe.jpeg)

**Comment by JaspalSuri** [comment]
Hi @OddHouseGames, thanks for the feedback! I'll take note of this. 🙂
