### ISSUE TITLE
Unable to use update any posts after adding a custom domain

### ISSUE THREAD

**Issue by lissy93** [standardnotes/listed#177]
Hi,
I'm not sure if it's just me (if so, feel free to close), but I'm having an issue where I can't publish or update private or public posts on the public hosted instance of Listed. I've tried on both the desktop and web versions, and using different networks and different devices.

![listed-error](https://user-images.githubusercontent.com/1862727/116812458-bd7bce00-ab46-11eb-9342-6b29872c82f0.PNG)

The only thing I have changed, is that I tried to add a custom domain (`notes.aliciasykes.com`), although doesn't seem to be working, but my main blog (`listed.to/@lissy93`) is still running just fine. I believe that's the source of the issue, as the network tab shows that it's calling the new domain.

Could it just be that the DNS take a while to propagate? Or is my only option to scrap the custom domain idea?

![listed-error2](https://user-images.githubusercontent.com/1862727/116812801-84dcf400-ab48-11eb-84e2-c163b0655fc3.PNG)

Thanks very much,
Alicia :)

**Edit:** Actually I think my blog is just broken. The homepage loads, but none of the posts do. Is there anything else that I needed to do, other than add an `A` record, for the domain to work correctly?

**Comment by lissy93** [comment]
Update: After removing the custom domain, it now works fine, so I guess this isn't an issue with Listed.
I would really like to use my domain, is there anything else I needed to do to get it working, other than point the `A` record to Listed's IP?

**Comment by atmoio** [comment]
You'd need to set up the DNS records and also wait for a confirmation email from us that the custom domain was configured correctly. Be sure you have a verified email on account.

**Comment by JaspalSuri** [comment]
Hi @Lissy93, I just wanted to follow up with you on this issue to see if it has been resolved. 🙂

**Comment by lissy93** [comment]
Thanks for checking up @JaspalSuri - Turns out to have been caused by the domain being proxied through Cloudflare - as soon as I disabled that, things worked perfectly. So totally my error, and not a bug at all.

If anyone else has trouble with something similar in the future, it might help to check that it's not a CF domain, as those are proxied through Cloudflare by default.

**Comment by JaspalSuri** [comment]
Sorry to hear that, but thank you for letting us know, @Lissy93. 🙂 I'll take note of this.
