### ISSUE TITLE
[Help Wanted] [Listed] Custom CSS for individual posts?

### ISSUE THREAD

**Issue by pseudolym** [standardnotes/listed#206]
Hi, is it possible to add custom CSS (that varies from my `listed-theme.css`) for individual Listed posts via metadata fields?

**Comment by JaspalSuri** [comment]
Hi @pseudolym, if you use the Plus or Bold Editors, you can use in-line CSS to customize your posts. I will check with the dev team to see if this can be set elsewhere.

**Comment by JaspalSuri** [comment]
Hi @pseudolym, the dev team has confirmed that customizing the CSS of individual posts would requiring setting in-line styling rules.

**Comment by pseudolym** [comment]
Got it, thank you!

**Comment by JaspalSuri** [comment]
You're very welcome!
