### ISSUE TITLE
[Listed.to] Reference to "Extended" plan in Custom domain settings

### ISSUE THREAD

**Issue by kashav** [standardnotes/listed#216]
The text refers to an "Extended" plan, but that plan doesn't seem to exist (based on https://standardnotes.com/plans). Maybe this should be "Plus" instead?

> Custom domains are available for Standard Notes **Extended** members with an active one year or five year plan. Domains include an HTTPS certificate, and require only a simple DNS record on your end.

**Comment by vardan-arm** [comment]
Hi @kashav , thank you for pointing out the obsolete description! It's updated now.
> Oh, I guess "Extended" just means <anything above "Core"> here? 

Correct, it's either "Plus" or "Pro" plan in case of custom domains.
