### ISSUE TITLE
Listed.to session cookie doesn't have Secure flag set

### ISSUE THREAD

**Issue by salixh5** [standardnotes/listed#220]
**Describe the bug**
On listed.to pages and on custom domains, there is a session cookie sent (_listed_session) but it does not have the Secure flag set (it does have HttpOnly set, so that is good). That could make session hijacking easier in (admittedly) very specific situations.

**To Reproduce**
1. Go to listed.to
2. Look at the cookie header

**Comment by atmoio** [comment]
Fixed in https://github.com/standardnotes/listed/commit/91504def3b60e3fdd320951d22f7ccde9fdd9f4e
