### ISSUE TITLE
listed.to homepage not update 

### ISSUE THREAD

**Issue by ncang** [standardnotes/listed#229]
Hello superb team,
I watched it for a long time, it seems that the listed.to homepage is a little buggy, doesn't display "recent author" like before... Is this problem related to rss or xml?

**Comment by stefan-yas** [comment]
Hey @ncang, this seems to be working fine for me at the moment - could you check again?

**Comment by ncang** [comment]
yeah the homepage seem working fine, but not updated like before... example if we published new post automatically appear in homepage listed.to

**Comment by ncang** [comment]
ah gotcha, it's about bio settings listed.to /authors/
thx @stefan-yas ,
i'll close this
