### ISSUE TITLE
How do you change custom domains?

### ISSUE THREAD

**Issue by ceiphr** [standardnotes/listed#5]
Hi I haven't really used listed but I've decided I'm going to utilize it as a change log for projects. I currently have it set up under https://blog.ceiphr.com. 

I want to change that to https://changelog.ceiphr.com.

I updated my DNS and am curious how your system will recognize this change as once a custom domain is configured I don't seem to have any extra settings to reconfigure it.

Thank you.

**Comment by atmoio** [comment]
You'd just have to let me know. I've went ahead and updated that for you.

**Comment by ceiphr** [comment]
Thank you, I appreciate it!

**Comment by lissy93** [comment]
In the future, it would be really useful to be able to do this through the UI

**Comment by JaspalSuri** [comment]
Noted! Currently you can do this mostly through the UI, but it will require a bit of a wait as someone from the team will have to set it up manually (usually within 24-48 hours; Monday through Friday). 

Open the desktop or web app (and log in) > click on the `Actions` menu (if the Listed extension has been installed) > and then click on `Settings` beneath the `Listed` section. A page to your Listed's settings should open in your default browser and the form to submit your Extended Email and Custom Domain will be available towards the very bottom of the page.

![image](https://user-images.githubusercontent.com/44656000/93834192-d5de4e80-fc2f-11ea-92f5-a0145e8443a1.png)
