### ISSUE TITLE
[Bug] inconsistency in how code tag is rendered

### ISSUE THREAD

**Issue by RemiDesgrange** [standardnotes/listed#55]
See : https://listed.to/@rdesgrange/18088/test-css

I don't know if this is intentional, but code tag render is not consistent troughout list. I think that the CSS rule responsible of that is [here](https://github.com/standardnotes/listed/blob/develop/app/assets/stylesheets/posts.scss#L119) but not an expert.

**Comment by RemiDesgrange** [comment]
see #57

**Comment by JaspalSuri** [comment]
Thanks for providing a direct link to the line that you believe to be the root of the issue! I've added it to my previous report and have asked the dev team to look into it.
