### ISSUE TITLE
Publish to blog not working

### ISSUE THREAD

**Issue by cxnky** [standardnotes/listed#6]
When I click "Publish to Blog" and "Publish to Private Link", it acts as if it is doing something but then just stops. [gif](https://netflix.is-a-vir.us/eiguc9ae.gif)

edit: i cant do markdown
edit 2: i still cant do markdown

**Comment by atmoio** [comment]
Please share what you see in the developer console when you perform these actions.

**Comment by cxnky** [comment]
There is nothing written to the console when I click either of the buttons.

**Comment by atmoio** [comment]
This should be fixed now. Was an issue with custom domain users.
