### ISSUE TITLE
[Feature-Request] - Specify how many posts to be visible per page/ remove 15-post cap

### ISSUE THREAD

**Issue by lissy93** [standardnotes/listed#62]
It would be really useful to be able to specify in the user settings to have more than 15 posts visible at a time. As, for blogs that only have the title visible, or have shorter posts, it ends up looking quite weird to only be able to view a few lines at a time. 
For example: https://listed.to/@lissy93

Btw, really awesome work you've done on both Listed and Standard Notes, I really love it!

**Comment by atmoio** [comment]
Hmm, yeah, true, this could be useful as a setting. We'll keep this one in mind! We're working on a big Listed redesign right now so perhaps can consider this feature as part of that big release. (cc @antsgar)

p.s. thanks for sponsoring us 💜

**Comment by lissy93** [comment]
Closing this, as is no longer applies/ was fixed in the new version of Listed. Great work guys :)
