### ISSUE TITLE
Base64 data image not rendered

### ISSUE THREAD

**Issue by frvkl** [standardnotes/listed#7]
When using Base64 encoded data images (*text only images*), within my markdown notes, as such:

```
![](data:image/png;base64,{{encoded-string-here}})
```

..they render perfectly within standard notes, but on listed published pages the "src" stays empty  within the img tag.

If this could be solved, that would be fantastic.

**Comment by atmoio** [comment]
I'd have to look into this. Probably being stripped to clean the text. Although I don't generally recommend storing base64 images in Standard Notes, as if you unexpectedly have a 2mb base64 image in text, it could cause performance reductions across the entire app, and especially on load.

**Comment by frvkl** [comment]
Thank you. I agree that base64 images should be used wisely. 
I use them for screen snippets in short term working notes. 
This avoids the need for managing a cloud folder with temporary images. 
I sometimes share these notes with some colleagues in our communication. Therefore I would really appreciate a fix in parsing these in Listed.

**Comment by atmoio** [comment]
I don't have any bandwidth for this issue any time soon, but feel free to look into it if you'd like to see if you can find a solution. This might be a good place to start: https://github.com/standardnotes/listed/blob/master/app/models/post.rb#L46

**Comment by frvkl** [comment]
It is okay for now. I will stop using base64 images for now. Just something to consider in the future. 👍
