### ISSUE TITLE
RFE:  Anon / isolated publish

### ISSUE THREAD

**Issue by kfiresmith** [standardnotes/listed#83]
I'd like to be able to anonymously publish things "off-blog" that would be published separate from my Listed "blog" with no obvious traceability back to me.

I have various highly formatted markdown notes that go beyond what could be done in a pastebin post, that I'd like to be able to link to within various tech/coding communities w/o the linked post revealing the rest of my blog as a use-case example.

**Comment by atmoio** [comment]
You can "Publish to private link". This will no have public traceability back to you. (Internally however in the database it will be connected to your account). If you want full anonymity you can create a separate Listed author account and publish to that one.

**Comment by kfiresmith** [comment]
Hi There,
Using the Linux AppImage w/ the Listed extension, I don't see an option for that.  Is this maybe something that isn't present on the extension on "lesser" platforms?

**Comment by kfiresmith** [comment]
Through a bit more digging it looks like I can see the option now at the outset to publish to private link - I think there is only the option to do this once at the outset of the publish.  It's a bit less flexible than I'd like but it'll do.
