### ISSUE TITLE
Shared Note was deleted, but is still accessible through Listed

### ISSUE THREAD

**Issue by frvkl** [standardnotes/listed#9]
Good Day,

I have a shared a note with a private link. The original note has been deleted (also from the Standard Note Trash section). The note, is still accessible through Listed if you have the private link.  Is there a way to remove the share on a deleted note if the note is no longer present in the Standard Notes interface?

Looking foward to hearing back from you.

**Comment by atmoio** [comment]
You can delete this post by opening your Listed Settings page, then finding it in the list of published posts. You should see a Delete option there.

**Comment by frvkl** [comment]
I found it. Thank you so much!
